from time import sleep
thao = (" thao : Hi daring")
print(thao)
sleep(2) 
me = (" me : Hi! Thao")
print(me)
sleep(2)
me = (" sorry beacause I disturbed your sleep")
print(me)
sleep(2)
me = ("I want to say")
print(me)
sleep(2)
me = ("I like you")
print(me)
sleep(2)
me =("and, I love you")
print(me)
sleep(2)
me =("goodbye, I go to bed")
print(me)
sleep(2)
me = ("Good night Thao")
print(me)
sleep(3)
